### ISSUE TITLE
Sometimes printer is not found during IP scan

### ISSUE THREAD

**Issue by XekriRedmane** [RobertBaruch/binvenio#1]
Maybe 200msec per IP address is not enough sometimes. I should increase to 500msec to see if that's more reliable. If so, I should also provide a way for the user to enter the IP address themselves, in case it's static or they otherwise know it and don't want to sit through a whole discovery.

**Comment by XekriRedmane** [comment]
Increased timeout to 500, scan worked about 70% of the time.

**Comment by XekriRedmane** [comment]
Increased timeout to 1000. Got an instance of a connection, but then a read timeout (100ms). Will increase to 500ms.

**Comment by XekriRedmane** [comment]
Got several instances of connection failure. However, when connecting from a wired computer, the connection succeeded immediately. I suspect there's something going on in the Android side.

**Comment by XekriRedmane** [comment]
I disconnected from the network and then reconnected, and failed to connect to the printer eight times in a row. It wasn't until nearly 1m30s from the first try that I was able to connect. I'm kind of at a loss to understand why the network is so unreliable.

**Comment by krasin** [comment]
Does your printer have Ethernet port? I begin to suspect that Zebra WiFi module is not as great as their printing stuff.

**Comment by XekriRedmane** [comment]
It doesn't :( I have noticed that the green WiFi symbol on the printer sometimes flashes red, as if it momentarily got disconnected. The Wifi module could be flaky.

**Comment by krasin** [comment]
It actually sounds a lot like I WiFi issues I had with the more expensive Zebras which have a screen. I guess, WiFi is too modern for the industry...

**Comment by XekriRedmane** [comment]
So far it looks like changing the printer's IP from DHCP to static, and reserving that address on the router, is working. It's more stable, anyway.

**Comment by XekriRedmane** [comment]
Closing this out, since I haven't seen this issue for several days since I changed the printer's IP to static.

**Comment by krasin** [comment]
is there a way for the app to query the printer for network settings and surface concerns to the user, if zebra is on dhcp?

**Comment by krasin** [comment]
basically, i am trying to find a way to codify your findings, so that nobody else gets hurt because of this issue.

**Comment by XekriRedmane** [comment]
Apparently this command will tell you if the printer has DHCP on or off:

`! U1 getvar "ip.dhcp.enable"`

Response is
`"off"`
or
`"on"`

If we scan for the printer and find it, I can add that command and maybe warn the user that DHCP may lead to unreliability.
