### ISSUE TITLE
Support for GX420d printer

### ISSUE THREAD

**Issue by XekriRedmane** [RobertBaruch/binvenio#10]
Apparently this printer does not have port 6101, but does have port 9100. ZPL works, but SGD (JSON) does not. Only plain old SGD works.

Therefore, I will have to scan for port 6101 first, then port 9100, which is unfortunate because many other printers will also respond on that port (9100 is the [JetDirect port](https://en.wikipedia.org/wiki/JetDirect)). But, we use the response to the host identification command `~HI` to attempt to recognize a Zebra printer. Note that the ZD410 responds on both 9100 and 6101, so maybe I should just stick with port 9100 for all printers? That seems to be the default.

In addition, sending `! U1 getvar "ip.dhcp.enable"` results in `"on"` even though I have DHCP off in the GX420d, and _that's not cool_. Instead, I have to send `! U1 getvar "internal_wired.ip.protocol"` which will return `"permanent"` if the IP address is permanent. The ZD410 responds with `"all"` to this command, so unfortunately the command will have to be different depending on model.

**Comment by krasin** [comment]
Ugh. Complexity.

Count me as surprised, though.

**Comment by XekriRedmane** [comment]
In addition, I'm having a hard time getting the GX420d to feed exactly one 0.5" label. It seems to feed 4". Using the `~JG` command I can see that the sensor is properly sensing the web between the labels.

**Comment by XekriRedmane** [comment]
There is even a manual calibration procedure described in the user's manual, and that fails.

**Comment by krasin** [comment]
Very strange.

**Comment by XekriRedmane** [comment]
Interesting. There's a command `~JL` which "sets the label length". Apparently this actively looks for the web and then sets the label length based on that. And now it is properly detecting the label size. I don't know why the ZD410 worked out of the box, but the label length had to be set on the GX420d.

**Comment by krasin** [comment]
Nice find!

**Comment by XekriRedmane** [comment]
I also don't see a way to easily query the maximum width of the printer, so I'll just have to store a table :(

**Comment by XekriRedmane** [comment]
Yeah, that's annoying. My laser printer prints "`~HI`" when I probe it on port 9100. Maybe I should require that you set up your printer for port 6101.

**Comment by krasin** [comment]
I think it's reasonable to rely on 6101. Eventually, when we get enough users, it might be a good idea to implement a better detection and auto-configuration, but this seems to be premature at this point.

**Comment by XekriRedmane** [comment]
I found that if a printer has a port 9100, and it responds to a `@PJL INFO ID` command, so that eliminates the port from possibility of being a Zebra printer.

**Comment by XekriRedmane** [comment]
I'm also curious whether different printers (even of the same model) will detect the label roll's web in a different place, so the positioning of the print has to be fine-tuned? Because the print on the GX420d is definitely lower than on the ZD410.

**Comment by XekriRedmane** [comment]
I coded it so that the top-left point for the sticker depends on the printer. If this turns out to be an issue, file a bug!
