### ISSUE TITLE
Sometimes print sticker fails silently

### ISSUE THREAD

**Issue by XekriRedmane** [RobertBaruch/binvenio#2]
Says "Printing sticker..." but then nothing happens, and there is no error message. Suspect needs more than 200msec to connect. Try 500msec.

**Comment by XekriRedmane** [comment]
Possibly related to #1

**Comment by XekriRedmane** [comment]
Closing this out with #1.

**Comment by krasin** [comment]
is there a way to check if the previous label is printed? One way to implement that is to get a count og printed labels somehow. Not sure if ZPL supports that

**Comment by XekriRedmane** [comment]
To be clear, what happens is that we display a snackbar that says `Printing sticker...` and then after we send the data to the printer, we display another snackbar that says `Sticker printed!`

The bug was that we'd only get the first snackbar. This is consistent with not being able to connect to the printer in the first place. Once we connect, I have never had the printer not print a sticker. However, a confirmation would be nice if I can find one in the ZPL manual.

**Comment by XekriRedmane** [comment]
I think using `^HV` inside the `^XA...^XZ` block might send a positive confirmation that a label was printed.

**Comment by krasin** [comment]
That would be nice to have, even if not immediately. It feels like a good P2 feature request.
